/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cmu.ri.airboat.enduser;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author pscerri
 */
public class IntelligencePanel extends javax.swing.JPanel {

    boolean running = false;
    
    /**
     * Creates new form IntelligencePanel
     */
    public IntelligencePanel() {
        initComponents();
        
        algC.setModel(new DefaultComboBoxModel(IntelligenceAlgorithms.Algorithm.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        algC = new javax.swing.JComboBox();
        startB = new javax.swing.JButton();
        allCB = new javax.swing.JCheckBox();
        liveB = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Intelligence"));

        algC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        startB.setText("Start");
        startB.setEnabled(false);
        startB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBActionPerformed(evt);
            }
        });

        allCB.setText("All");
        allCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCBActionPerformed(evt);
            }
        });

        liveB.setText("Live Data");
        liveB.setEnabled(false);
        liveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liveBActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(algC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(startB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(allCB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(62, 62, 62)
                        .add(liveB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(algC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(startB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(allCB)
                    .add(liveB))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBActionPerformed
        
        // @todo Enable startB at the right moment
        running = !running;
        if (running) {
            startB.setText("Stop");
  
            if (allCB.isSelected()) {
                (new IntelligenceAlgorithms()).startAutonomyAll();
            } else {
                (new IntelligenceAlgorithms()).startAutonomyProxy();
            }
        } else {
            startB.setText("Start");
            
            // @todo Implement stop
        }
    }//GEN-LAST:event_startBActionPerformed

    private void allCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCBActionPerformed
        // @todo Implement allChecked
        System.out.println("All checked");
        if (running) {
            if (allCB.isSelected()) {
                (new IntelligenceAlgorithms()).startAutonomyAll();
            }
        } else {
            // @todo Stop all autonomy
        }
    }//GEN-LAST:event_allCBActionPerformed

    private void liveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liveBActionPerformed
        (new IntelligenceAlgorithms()).showDataDisplay();
    }//GEN-LAST:event_liveBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox algC;
    private javax.swing.JCheckBox allCB;
    public javax.swing.JButton liveB;
    public javax.swing.JButton startB;
    // End of variables declaration//GEN-END:variables
}
